# Problem 1:
Calculate matrix product manually.
A = [-1, 2 ,3]   B = [0, 2, 1]
    [ 4 ,-5, 6 ]     [0, 2, -8]
     [7, 8, -9]      [2, 9, -1]



Solve the multiplication of matrix (A x B) manually
1. To calculate the first element of 1st row, we multiply and add the elements of the 1st row of A = A[0,:] with 1st column of B = B[:,0]
(-1,2,3).(0,0,2) = (-1*0) + (2*0) + (3*2) = 6
2. To calculate second element of 1st row A[0,:] * B[:,1]
(-1,2,3).(2,2,9) = (-1*2) + (2*2) + (3*9) = 29
3. To calculate third element of 1st row A[0,:] * B[:,2]
(-1,2,3).(1,-8,-1) = (-1*1) +(2*-8) + (3*-1) = -20
4. We do the same for other rows: Row2
(4,-5,6).(0,0,2) = (4*0) + (-5*0) +(6*2) = 12
(4,-5,6).(2,2,9) = (4*2) + (-5*2) + (6*9) = 52
(4,-5,6).(1,-8,-1) = (4*1) + (-5*-8) + (6*-1)= 38
5. Row 3
(7,8,-9).(0,0,2) = (7*0) + (8*0) + (-9*2) = -18
(7,8,-9).(2,2,9) = (7*2) + (8*2) + (-9*9) = -51
(7,8,-9).(1,-8,-1) = (7*1) + (8*-8) + (-9*-1) = -48

Answer: [6, 29, -20]
        [12, 52, 38]
        [-18,-51,-48]


# Problem 2:
Calculation with Numpy functions

In [1]:
#using np.matmul()
import numpy as np
a = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
b = np.array([[0,2,1],[0,2,-8],[2,9,-1]])
np.matmul(a,b)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [2]:
#using np.dot()
import numpy as np
a = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
b = np.array([[0,2,1],[0,2,-8],[2,9,-1]])
np.dot(a,b)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# Problem 3:
Scratch implementation of matrix multiplication of matrix A and B

In [13]:
a = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
b = np.array([[0,2,1],[0,2,-8],[2,9,-1]])

ab_list= [[((a[0,0]*b[0,0]) + (a[0,1]*b[1,0]) + (a[0,2]*b[2,0])),
 ((a[0,0]*b[0,1]) + (a[0,1]*b[1,1]) + (a[0,2]*b[2,1])),
 ((a[0,0]*b[0,2]) + (a[0,1]*b[1,2]) + (a[0,2]*b[2,2]))],
 [((a[1,0]*b[0,0]) + (a[1,1]*b[1,0]) + (a[1,2]*b[2,0])),
 ((a[1,0]*b[0,1]) + (a[1,1]*b[1,1]) + (a[1,2]*b[2,1])),
((a[1,0]*b[0,2]) + (a[1,1]*b[1,2]) + (a[1,2]*b[2,2]))],
[((a[2,0]*b[0,0]) + (a[2,1]*b[1,0]) + (a[2,2]*b[2,0])),
((a[2,0]*b[0,1]) + (a[2,1]*b[1,1]) + (a[2,2]*b[2,1])),
((a[2,0]*b[0,2]) + (a[2,1]*b[1,2]) + (a[2,2]*b[2,2]))]]

ab = np.array(ab_list)
ab

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [14]:
#Another way to calculate problem 3
a = [[-1,2,3],[4,-5,6],[7,8,-9]]
b = [[0,2,1],[0,2,-8],[2,9,-1]]
ab_list = []

for i_row in range(0,3):
    temp_list = []
    for j in range(0,3):
        sum_ab = 0
        for k_col in range(0,3):
            sum_ab = sum_ab + (a[i_row][k_col]*b[k_col][j])
        temp_list.append(sum_ab)
    ab_list.append(temp_list)
for row in ab_list:
    print(row)

[6, 29, -20]
[12, 52, 38]
[-18, -51, -48]


# Problem 4:
Creating a function that performs matrix multiplication. It receives matrices A and B as arguments and returns the matrix product.

In [24]:
def matrix_multiplier(a,b):
    d = np.array(a) # converts a to np array so as to get no. of rows
    e = np.array(b) # converts b to np array so as to get no. of columns
    rows = len(d[:,0]) # get no. of rows
    columns = len(e[0,:]) # get no. of columns
    ab_list = [] # create an empty list to hold the new matrix
    for i_row in range(0,rows):
        temp_list = []  
        for j in range(0,rows):
            sum_ab = 0 
            for k_col in range(0,columns):
                sum_ab = sum_ab + (a[i_row][k_col]*b[k_col][j])
            temp_list.append(sum_ab) # temporary list to hold elements of matrix
        ab_list.append(temp_list) # append the elements to matrix
    for row in ab_list:
        print(row)
        
matrix_multiplier(([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]),([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]))

[90, 100, 110, 120]
[202, 228, 254, 280]
[314, 356, 398, 440]
[426, 484, 542, 600]


# Problem 5:
Judge the input whose calculation is not defined
If using our function above in problem 4 we multiply 2 matrices that are not defined.

In [25]:
def matrix_multiplier(a,b):
    d = np.array(a) # converts a to np array so as to get no. of rows
    e = np.array(b) # converts b to np array so as to get no. of columns
    rows = len(d[:,0]) # get no. of rows
    columns = len(e[0,:]) # get no. of columns
    ab_list = [] # create an empty list to hold the new matrix
    for i_row in range(0,rows):
        temp_list = []  
        for j in range(0,rows):
            sum_ab = 0 
            for k_col in range(0,columns):
                sum_ab = sum_ab + (a[i_row][k_col]*b[k_col][j])
            temp_list.append(sum_ab) # temporary list to hold elements of matrix
        ab_list.append(temp_list) # append the elements to matrix
    for row in ab_list:
        print(row)
        
matrix_multiplier([[-1,2,3],[4,-5,6]],[[-9,8,7],[6,-5,4]])

IndexError: list index out of range

Following multiplication of 2 undefined matrices an error occurs and we get a message index out of range which might be hard to understand ,to solve this: We use if statement, if number of rows and columns are not equal then a message is printed out indicating an error.

In [31]:
def matrix_multiplier(a,b):
    d = np.array(a) # converts a to np array so as to get no. of rows
    e = np.array(b) # converts b to np array so as to get no. of columns
    rows = len(d[:,0]) # get no. of rows
    columns = len(e[0,:]) # get no. of columns
    if (rows == columns):
        ab_list = [] # create an empty list to hold the new matrix
        for i_row in range(0,rows):
            temp_list = []  
            for j in range(0,rows):
                sum_ab = 0 
                for k_col in range(0,columns):
                    sum_ab = sum_ab + (a[i_row][k_col]*b[k_col][j])
                temp_list.append(sum_ab) # temporary list to hold elements of matrix
            ab_list.append(temp_list) # append the elements to matrix
        for row in ab_list:
            print(row)
    else:
        print("The matrix product is not defined, so it cannot be calculated!")
        
matrix_multiplier([[-1,2,3],[4,-5,6]],[[-9,8,7],[6,-5,4]])

The matrix product is not defined, so it cannot be calculated!


# Problem 6:
Transposition.
Transposing one matrix allows you to calculate the matrix product

In [34]:
#using our earlier undefined matrices
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
#if we transpose e using np.transpose()
print(np.transpose(e_ndarray))
# if we transpose e using .T
print(e_ndarray.T)

[[-9  6]
 [ 8 -5]
 [ 7  4]]
[[-9  6]
 [ 8 -5]
 [ 7  4]]


we get similar results
if we pass D and transposed E to our function 


In [35]:
def matrix_multiplier(a,b):
    d = np.array(a) # converts a to np array so as to get no. of rows
    e = np.array(b) # converts b to np array so as to get no. of columns
    rows = len(d[:,0]) # get no. of rows
    columns = len(e[0,:]) # get no. of columns
    if (rows == columns):
        ab_list = [] # create an empty list to hold the new matrix
        for i_row in range(0,rows):
            temp_list = []  
            for j in range(0,rows):
                sum_ab = 0 
                for k_col in range(0,columns):
                    sum_ab = sum_ab + (a[i_row][k_col]*b[k_col][j])
                temp_list.append(sum_ab) # temporary list to hold elements of matrix
            ab_list.append(temp_list) # append the elements to matrix
        for row in ab_list:
            print(row)
    else:
        print("The matrix product is not defined, so it cannot be calculated!")
        
matrix_multiplier([[-1,2,3],[4,-5,6]],[[-9,6],[8,-5],[7,4]])

[25, -16]
[-76, 49]


Since the matrix is defined after transposition we get a value.